 - repo: https://github.com/keep-network/pre-commit-hooks.git
   rev: v1.3.0
   hooks:
    - id: check-added-large-files
 - repo: local
   hooks:
    - id: lint-js
      name: 'lint js'
      entry: /usr/bin/env npm run lint:js
      files: '\.js$'
      language: script
      description: "Checks JS code according to the package's linter configuration"
